feat:   * support font, djvu, Epub and MOBI preview.
enhanced:
  * improve the performance of `pre`.
  * enhance the preview interface for tar(.gz) and zip archives.
  * change the cache function - `thumb_cache`.

fix:
  * wrong implement of `img_preview_fix` function.

docs:
  * fix some typos.
  * add more notes.

diff --git a/pre b/pre
--- a/pre
+++ b/pre
@@ -1,33 +1,67 @@
 #!/usr/bin/env zsh
 
-# NOTE: Dependency:
-# 1. chafa    - preview image in terminal
-# 2. eza      - preview directory structure
-# 3. tree     - preview zip/tar structure
-# 4. pdftoppm - convert pdf to PNG-format image
-# 5. bat      - preview text/source files
-# 6. ffmpegthumbnailer - video thumbnailer preview
+# WARNING:
+#   before clear the cache folder '~/.cache/pre_thumbs',
+#   run 'umount ~/.cache/pre_thumbs/mnt' first !!!
+ 
+# Dependency:
+#   1. chafa    - print image in terminal(kernel)
+#   2. eza      - preview directory
+#   3. bat      - preview text/source files
+#   4. pdftoppm - preview pdf files
+#   5. ddjvu    - preview djvu files
+#   6. magick   - preview fonts
+#   7. ffmpegthumbnailer      - preview videos
+#   8. archivemount/fuse-zip  - preview tar(.gz) or zip files
+#   9. gnome-epub-thumbnailer - preview EPub or MOBI books
+
 
 local file="$1"
 local ext="${file:l}"
-local view_size="x16" # 'WxH' -> set width automatically
+local view_size="x17" # 'WxH' -> set width automatically
 local cache_dir="$HOME/.cache/pre_thumbs"
+local mnt_point="$HOME/.cache/pre_thumbs/mnt"
 # local cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/pre_thumbs"
 local MAX_DIR_ITEMS=200
 local MAX_FIX=3
+# eza argument
+# usage: export EZA_ARG="-T --icons"
+if [[ -n "$EZA_ARG" ]]; then
+    local eza_arg=(${=EZA_ARG})
+else
+    local eza_arg=(-Tlb --icons=always --color=always)
+fi
+# font preview text
+# usage: export FONT_TEXT="Hello, world."
+if [[ -n "$FONT_TEXT" ]]; then
+    local font_text="$FONT_TEXT"
+else
+    local font_text="ABCDEFGH\n0123456789\nabcdefgh"
+fi
+
+
+# make cache dir
+mkdir -p "$cache_dir"
+mkdir -p "$mnt_point"
 
 
 # thumb image cache
-mkdir -p "$cache_dir"
-thumb_cache_path() {
+if [[ -f "$cache_dir/default_salt" ]]; then
+    local salt_default="$(cat $cache_dir/default_salt)"
+else
+    echo "$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)" \
+         > "$cache_dir/default_salt"
+fi
+thumb_cache() {
     local file="$1"
     local prefix="$2"
     local gen_cmd="$3"
+    local hash_salt="$4" # add salt to HASH
 
     # cache label
     local mtime key
     mtime=$(stat -c %Y "$file" 2>/dev/null) || return 1
-    key=$(printf "%s_%s" "$file" "$mtime" | md5sum | awk '{print $1}')
+    key=$(printf "%s_%s_%s" "$file" "$mtime" "$hash_salt" | md5sum | awk '{print $1}')
 
     # if not-cached, generate it
     local img="$cache_dir/${prefix}_${key}.png"
@@ -43,6 +77,7 @@ gen_video_thumb() {
     local img="$2"
     ffmpegthumbnailer -s 0 -i "$file" -o "$img" &>/dev/null
 }
+
 gen_pdf_thumb() {
     local file="$1"
     local img="$2"
@@ -51,37 +86,60 @@ gen_pdf_thumb() {
              "$file" "${img%.png}" >/dev/null 2>&1
 }
 
-# auto re-generate for damaged picture
+gen_djvu_thumb() {
+    local file="$1"
+    local img="$2"
+    ddjvu -format=tiff -page=1 "$file" "$img" >/dev/null 2>&1
+}
+
+gen_epmo_thumb() { # Epub & MOBI
+    local file="$1"
+    local img="$2"
+    gnome-epub-thumbnailer "$file" "$img" >/dev/null 2>&1
+}
+
+gen_font_thumb() {
+    local file="$1"
+    local img="$2"
+    magick -gravity center -size 400x400 \
+           -background "#ffffff" -fill "#000000" \
+           -font "$file" caption:"$font_text" \
+           "$img"
+}
+
+
+# auto re-generate(fix) for damaged picture
 img_preview_fix() {
     local file="$1"
     local img="$2"
     local gen_cmd="$3"
+    local success=0
 
     # auto fix damaged picture 'MAX_FIX' times
-    if ! chafa --size=$view_size --animate=off "$img"; then
-        echo "$img" | wl-copy 
-        for ((i=1; i<=$MAX_FIX; i++)); do
-            if [[ -f "$img" ]]; then
-                rm -f "$img" 
+    # echo "$img" | wl-copy
+    for ((i=1; i<=$MAX_FIX; i++)); do
+        if [[ -f "$img" ]]; then
+            if ! chafa --size=$view_size --animate=off "$img"; then
+                rm -f "$img"
+                "$gen_cmd" "$file" "$img"
+            else
+                chafa --size=$view_size --animate=off "$img"
+                success=1
+                break
             fi
+        else
             "$gen_cmd" "$file" "$img"
-        done
-        chafa --size=$view_size --animate=off "$img"
-    else
-        chafa --size=$view_size --animate=off "$img"
+        fi
+    done
+    if [[ "$success" -eq 0 ]]; then
+        printf "\n\nERROR: Failed to generate preview image !"
     fi
 }
 
 
-# tar(.gz)/zip file discription
-compress_file_info() {
-    file "$file" | fmt -s
-    printf "\nContents structure:\n\n"
-}
-
 # check if 'file' is a directory
 if [[ -d "$file" ]]; then
-    eza -T --icons=always --color=always "$file" | head -$MAX_DIR_ITEMS
+    eza "${eza_arg[@]}" "$file" | head -$MAX_DIR_ITEMS
     return
 fi
 # match simple text file with NO ext
@@ -94,35 +152,54 @@ case "$ext" in
     *.txt|*.md|*.org|*.json|*.yaml|*.yml|*.log|*.c|*.cpp|*.h|*.py|*.sh|*.zsh|*.el|*.tex)
         bat --style=numbers --color=always --line-range :$MAX_DIR_ITEMS "$file"
         ;;
+
     # image
     *.png|*.jpg|*.jpeg|*.svg|*.gif|*.webp|*.bmp|*.tiff)
         chafa --size=$view_size --animate=off "$file"
         ;;
+
     # document
     *.pdf)
-        local img=$(thumb_cache_path "$file" "PDF" gen_pdf_thumb)
-        img_preview_fix "$file" "$img" gen_pdf_thumb 
+        local img=$(thumb_cache "$file" "PDF" gen_pdf_thumb "$salt_default")
+        img_preview_fix "$file" "$img" gen_pdf_thumb
         ;;
+    *.djvu)
+        local img=$(thumb_cache "$file" "DJVU" gen_djvu_thumb "$salt_default")
+        img_preview_fix "$file" "$img" gen_djvu_thumb
+        ;;
+    *.epub|*.mobi)
+        local img=$(thumb_cache "$file" "DJVU" gen_epmo_thumb "$salt_default")
+        img_preview_fix "$file" "$img" gen_epmo_thumb
+        ;;
+
+    # font
+    *.ttf|*.otf|*.ttc|*.otc|*.woff|*.woff2)
+        local img=$(thumb_cache "$file" "FONT" gen_font_thumb "$font_text")
+        img_preview_fix "$file" "$img" gen_font_thumb
+        ;;
+
     # video
     *.mp4|*.mkv|*.mov|*.mpv|*.avi|*.wmv|*.flv|*.webm|*.ts|*.m2ts|*.vob|*.3gp)
-        local img=$(thumb_cache_path "$file" "VIDEO" gen_video_thumb)
-        img_preview_fix "$file" "$img" gen_vedio_thumb 
+        local img=$(thumb_cache "$file" "VIDEO" gen_video_thumb "$salt_default")
+        img_preview_fix "$file" "$img" gen_vedio_thumb
         ;;
-    # tar(.gz)
+
+    # tar(.gz) & zip
     *.tar|*.tar.gz|*.tgz|*.tar.xz|*.txz|*.tar.bz2|*.tbz2)
-        compress_file_info
-        tar -tf "$file" | head -$MAX_DIR_ITEMS \
-            | tree --fromfile . \
-            | sed '1d' | head -n -2
+        if [[ ! -z "$(ls -A $mnt_point)" ]]; then
+            umount $mnt_point
+        fi
+        archivemount "$file" "$mnt_point" -o readonly,nosave
+        eza "${eza_arg[@]}" "$mnt_point" | head -$MAX_DIR_ITEMS
         ;;
-    # zip
     *.zip)
-        compress_file_info
-        unzip -l "$file" \
-            | head -$MAX_DIR_ITEMS | head -n -2 | tail -n -3 \
-            | awk '{print $NF}' | tree --fromfile . \
-            | sed '1d' | head -n -2
+        if [[ ! -z "$(ls -A $mnt_point)" ]]; then
+            umount $mnt_point
+        fi
+        fuse-zip -r "$file" "$mnt_point"
+        eza "${eza_arg[@]}" "$mnt_point" | head -$MAX_DIR_ITEMS
         ;;
+
     # others
     *)
         file "$file" | fmt -s
